---
name: Release
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'ci'
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot' && contains(github.ref, 'refs/heads/release/') }}
    steps:
      - name: Get tag
        run: echo '::set-output name=tag::'${GITHUB_REF#refs/heads/release/}
        id: get-tag-step
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: ${{ steps.get-tag-step.outputs.tag }}
          release_name: Release ${{ steps.get-tag-step.outputs.tag }}
          draft: false
          prerelease: false
